import { useEffect, useState } from "react"
import { useParams, useNavigate } from "react-router-dom"
import { ArrowLeft, Brain, ThumbsDown, ThumbsUp, Meh, Loader2, Sparkles } from "lucide-react"
import toast from "react-hot-toast"
import Sidebar from "../components/layout/Sidebar"
import RoadmapViewer from "../components/roadmap/RoadmapViewer"
import { usePathStore } from "../store/pathStore"
import { progress as progressApi, aiApi } from "../services/api"

export default function LearningPath() {
  const { pathId } = useParams()
  const { activePath, loadPath, isLoading } = usePathStore()
  const navigate = useNavigate()
  const [explanation, setExplanation] = useState(false)
  const [adaptingId, setAdaptingId] = useState(null)

  useEffect(() => { loadPath(pathId) }, [pathId, loadPath])

  const handleResourceComplete = async (milestoneId, resource, completed) => {
    try {
      await progressApi.update({ pathId, milestoneId, courseId: resource.courseId, status: completed ? "completed" : "in_progress", completionPct: completed ? 100 : 50 })
    } catch { toast.error("Failed to update progress") }
  }

  const handleAdapt = async (milestoneId, feedback) => {
    setAdaptingId(milestoneId)
    try {
      await aiApi.adaptMilestone({ pathId, milestoneId, feedback })
      await loadPath(pathId)
      toast.success("Milestone adapted based on your feedback!")
    } catch { toast.error("Failed to adapt milestone") }
    finally { setAdaptingId(null) }
  }

  if (isLoading) return (
    <div className="flex min-h-screen bg-gray-950">
      <Sidebar />
      <main className="flex-1 md:ml-64 flex items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin text-primary-400" />
      </main>
    </div>
  )

  if (!activePath) return (
    <div className="flex min-h-screen bg-gray-950">
      <Sidebar />
      <main className="flex-1 md:ml-64 flex items-center justify-center text-gray-400">Path not found.</main>
    </div>
  )

  return (
    <div className="flex min-h-screen bg-gray-950">
      <Sidebar />
      <main className="flex-1 md:ml-64 p-6">
        <button onClick={() => navigate("/dashboard")} className="flex items-center gap-2 text-gray-400 hover:text-white text-sm mb-6 transition-colors">
          <ArrowLeft className="h-4 w-4" /> Back to Dashboard
        </button>

        <div className="max-w-3xl mx-auto space-y-6">
          <div className="card">
            <div className="flex items-start justify-between gap-4">
              <div>
                <h1 className="text-2xl font-bold">{activePath.title}</h1>
                <p className="text-gray-400 mt-1">{activePath.goal}</p>
              </div>
              <span className={`badge shrink-0 px-3 py-1 ${activePath.status === "completed" ? "bg-green-900 text-green-300" : "bg-primary-900 text-primary-300"}`}>
                {activePath.status}
              </span>
            </div>
            <div className="mt-4 flex items-center gap-4 text-sm text-gray-400">
              <span>{activePath.totalWeeks} weeks</span>
              <span>·</span>
              <span>{activePath.milestones?.length} milestones</span>
              <span>·</span>
              <span>Generated by {activePath.generatedByModel}</span>
            </div>
          </div>

          {activePath.aiExplanation && (
            <div className="card border-primary-900 bg-primary-950/30">
              <button className="flex items-center gap-2 text-primary-400 text-sm font-medium w-full" onClick={() => setExplanation(!explanation)}>
                <Sparkles className="h-4 w-4" /> Why this path was recommended for you
                <span className="ml-auto text-xs text-primary-600">{explanation ? "hide" : "show"}</span>
              </button>
              {explanation && <p className="text-gray-300 text-sm mt-3 leading-relaxed">{activePath.aiExplanation}</p>}
            </div>
          )}

          <div>
            <div className="flex items-center justify-between mb-2">
              <h2 className="font-semibold flex items-center gap-2"><Brain className="h-4 w-4 text-primary-400" />Your Roadmap</h2>
              <p className="text-xs text-gray-500">Click a milestone to expand resources</p>
            </div>
            <RoadmapViewer path={activePath} onResourceComplete={handleResourceComplete} />
          </div>

          <div className="card">
            <h3 className="font-medium mb-3">Adapt this path</h3>
            <p className="text-gray-400 text-sm mb-4">Tell us how the current milestone feels and we will adjust it instantly.</p>
            <div className="flex gap-3 flex-wrap">
              {activePath.milestones?.filter((m) => !m.isCompleted).slice(0, 1).map((m) => (
                <div key={m._id} className="flex gap-2">
                  <button onClick={() => handleAdapt(m._id, "too_easy")} disabled={!!adaptingId} className="btn-secondary text-sm flex items-center gap-1">
                    {adaptingId === m._id ? <Loader2 className="h-3 w-3 animate-spin" /> : <ThumbsUp className="h-3 w-3 text-green-400" />} Too Easy
                  </button>
                  <button onClick={() => handleAdapt(m._id, "too_hard")} disabled={!!adaptingId} className="btn-secondary text-sm flex items-center gap-1">
                    {adaptingId === m._id ? <Loader2 className="h-3 w-3 animate-spin" /> : <ThumbsDown className="h-3 w-3 text-red-400" />} Too Hard
                  </button>
                  <button onClick={() => handleAdapt(m._id, "already_know")} disabled={!!adaptingId} className="btn-secondary text-sm flex items-center gap-1">
                    {adaptingId === m._id ? <Loader2 className="h-3 w-3 animate-spin" /> : <Meh className="h-3 w-3 text-yellow-400" />} Already Know
                  </button>
                </div>
              ))}
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
